export const GET_SHARES = 'GET_SHARE' 
export const INSERT_SHARE = 'INSERT_SHARE' 
export const FAV_SHARE = 'FAV_SHARE' 
export const UNFAV_SHARE = 'UNFAV_SHARE' 
export const COMMENT_SHARE = 'COMMENT_SHARE' 